In [1]:
#Selenium imports here
import selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait

In [2]:
#Other imports here
import os
import wget

import pandas as pd
from matplotlib import pyplot as plt

In [3]:
driver = webdriver.Chrome('C:/Users/User/Desktop/chromedriver.exe')
driver.get("https://brasileirao.cbf.com.br/jogos-da-rodada/1")

In [6]:
listaTimes = ["FLU", "SAN", "ACG", "FLA", "PAL", "CEA", "CFC", "GOI", "CAM", "INT", "BOT", "COR", "FOR", "CUI", "SAO", "CAP", "AVA", "AME", "JUV", "BRA"]
teams = {}
for i in listaTimes:
              teams[i] = {"id": i, "pontuacao": 0, "vitorias": 0, "empates":0, "derrotas": 0, "saldoDeGols":0, "golsPro": 0, "golsContra": 0, "golsProEmCasa": 0,"golsProFora": 0, "golsContraEmCasa": 0, "golsContraFora": 0}
        
for j in range (1,39):
    driver.get("https://brasileirao.cbf.com.br/jogos-da-rodada/"+str(j))
    getnomestimes=driver.find_elements_by_class_name("time_nome")
    lista_nome_times = []
    for i in getnomestimes:
        lista_nome_times.append(i.text)

    getgols=driver.find_elements_by_class_name("gols")
    lista_gols = []
    for i in getgols:
        lista_gols.append(i.text)
        
    if lista_gols[0] == "-\n-":
            break  
            
    print(f"{str(j)}ª RODADA")
    for i in range (0,10):
        print(lista_nome_times[i*2] + " " + lista_gols[i][0] + " x " + lista_gols[i][2] + " " + lista_nome_times[i*2+1])
        for j in lista_nome_times:
            if lista_nome_times[i*2] == j:
                teams[j]["golsProEmCasa"] += int(lista_gols[i][0])
                teams[j]["golsContraEmCasa"] += int(lista_gols[i][2])
                if int(lista_gols[i][0]) > int(lista_gols[i][2]):
                    teams[lista_nome_times[i*2]]["vitorias"] += 1
                    teams[lista_nome_times[i*2+1]]["derrotas"] += 1
                elif int(lista_gols[i][0]) < int(lista_gols[i][2]):
                    teams[lista_nome_times[i*2]]["derrotas"] += 1
                    teams[lista_nome_times[i*2+1]]["vitorias"] += 1
                else: 
                    teams[lista_nome_times[i*2]]["empates"] += 1
                    teams[lista_nome_times[i*2+1]]["empates"] += 1
            if lista_nome_times[i*2+1] == j:
                teams[j]["golsProFora"] += int(lista_gols[i][2])
                teams[j]["golsContraFora"] += int(lista_gols[i][0])
            
    print("\n")

for i in lista_nome_times:
    teams[i]["pontuacao"] = teams[i]["vitorias"]*3 + teams[i]["empates"]
    teams[i]["golsPro"] = teams[i]["golsProEmCasa"] + teams[i]["golsProFora"]
    teams[i]["golsContra"] = teams[i]["golsContraEmCasa"] + teams[i]["golsContraFora"]
    teams[i]["saldoDeGols"] = teams[i]["golsPro"] - teams[i]["golsContra"]
    teams[i]["saldoDeGolsEmCasa"] = teams[i]["golsProEmCasa"] - teams[i]["golsContraEmCasa"]
    teams[i]["saldoDeGolsFora"] = teams[i]["golsProFora"] - teams[i]["golsContraFora"]

1ª RODADA
FLU 0 x 0 SAN
ACG 1 x 1 FLA
PAL 2 x 3 CEA
CFC 3 x 0 GOI
CAM 2 x 0 INT
BOT 1 x 3 COR
FOR 0 x 1 CUI
SAO 4 x 0 CAP
AVA 1 x 0 AME
JUV 2 x 2 BRA


2ª RODADA
GOI 1 x 1 PAL
AME 4 x 1 JUV
COR 3 x 0 AVA
CUI 0 x 1 FLU
SAN 2 x 1 CFC
FLA 3 x 1 SAO
BRA 4 x 0 ACG
INT 2 x 1 FOR
CAP 0 x 1 CAM
CEA 1 x 3 BOT


3ª RODADA
BRA 1 x 1 SAO
CAP 1 x 0 FLA
FLU 0 x 1 INT
PAL 3 x 0 COR
CAM 2 x 2 CFC
SAN 3 x 0 AME
JUV 0 x 1 CUI
ACG 1 x 1 BOT
AVA 3 x 2 GOI
FOR 0 x 1 CEA


4ª RODADA
FLA 0 x 0 PAL
AME 1 x 0 CAP
CEA 0 x 1 BRA
GOI 2 x 2 CAM
CUI 1 x 1 ACG
BOT 1 x 1 JUV
COR 1 x 0 FOR
CFC 3 x 2 FLU
INT 0 x 0 AVA
SAO 2 x 1 SAN


5ª RODADA
CAM 1 x 2 AME
CAP 1 x 0 CEA
FLA 0 x 1 BOT
PAL 1 x 1 FLU
ACG 0 x 1 GOI
BRA 0 x 1 COR
SAN 4 x 1 CUI
JUV 1 x 1 INT
FOR 1 x 1 SAO
AVA 2 x 1 CFC


6ª RODADA
PAL 2 x 0 BRA
CEA 2 x 2 FLA
CAM 2 x 0 ACG
INT 2 x 2 COR
FLU 2 x 1 CAP
SAO 2 x 1 CUI
CFC 1 x 0 AME
BOT 3 x 1 FOR
AVA 1 x 2 JUV
GOI 1 x 0 SAN


7ª RODADA
BRA 1 x 1 CAM
FLA 1 x 0 GOI
ACG 2 x 0 CFC
SAN 0 x 0 CEA
JUV 0 x 3 PAL
AME 1 x 1 BOT
CUI 1 x 1 INT
COR 1 x 1 SAO
FOR 0 x 1 FLU
CAP 2 x 1 AVA


8ª RODADA
GOI 1 x 1 BRA
SAO 2 x 2 CEA
FOR 1 x 1 JUV
SAN 0 x 1 PAL
CFC 1 x 0 BOT
FLU 1 x 2 FLA
COR 1 x 1 AME
CUI 0 x 1 CAP
CAM 2 x 1 AVA
INT 1 x 1 ACG


9ª RODADA
AME 2 x 1 CUI
CEA 1 x 1 CFC
AVA 1 x 1 SAO
CAP 2 x 2 SAN
ACG 0 x 1 COR
JUV 1 x 0 FLU
FLA 1 x 2 FOR
PAL 0 x 0 CAM
BRA 0 x 2 INT
BOT 1 x 2 GOI


10ª RODADA
CUI 1 x 0 COR
AME 0 x 2 CEA
JUV 1 x 3 CAP
BRA 1 x 0 FLA
ACG 2 x 1 AVA
FLU 5 x 3 CAM
SAN 1 x 1 INT
PAL 4 x 0 BOT
FOR 1 x 1 GOI
CFC 1 x 1 SAO


11ª RODADA
COR 2 x 0 JUV
CAM 1 x 1 SAN
FLU 0 x 2 ACG
CUI 1 x 1 BRA
INT 3 x 1 FLA
SAO 1 x 0 AME
GOI 1 x 1 CEA
CFC 0 x 2 PAL
FOR 0 x 0 CAP
BOT 0 x 1 AVA


12ª RODADA
JUV 1 x 2 SAN
BRA 4 x 2 CFC
CEA 0 x 0 CAM
FLA 2 x 0 CUI
GOI 1 x 2 INT
AME 0 x 0 FLU
CAP 1 x 1 COR
BOT 1 x 0 SAO
PAL 4 x 2 ACG
AVA 3 x 2 FOR


13ª RODADA
CUI 0 x 0 CEA
SAN 2 x 2 BRA
CAM 2 x 0 FLA
COR 1 x 0 GOI
CFC 0 x 1 CAP
INT 2 x 3 BOT
FOR 1 x 0 AME
ACG 3 x 1 JUV
FLU 2 x 0 AVA
SAO 1 x 2 PAL


14ª RODADA
INT 3 x 0 CFC
CAP 4 x 2 BRA
FLA 3 x 0 AME
COR 0 x 0 SAN
CAM 3 x 2 FOR
BOT 0 x 1 FLU
AVA 2 x 2 PAL
SAO 0 x 0 JUV
CEA 1 x 1 ACG
GOI 1 x 0 CUI


15ª RODADA
FLU 4 x 0 COR
JUV 1 x 2 CAM
SAN 1 x 2 FLA
CEA 1 x 1 INT
PAL 0 x 2 CAP
AVA 1 x 2 CUI
ACG 1 x 2 SAO
AME 1 x 0 GOI
CFC 2 x 1 FOR
BRA 0 x 1 BOT


16ª RODADA
BRA 4 x 0 AVA
FLU 2 x 1 CEA
GOI 2 x 1 CAP
CFC 2 x 2 JUV
COR 1 x 0 FLA
CAM 0 x 0 SAO
SAN 1 x 0 ACG
FOR 0 x 0 PAL
CUI 2 x 0 BOT
INT 1 x 0 AME


17ª RODADA
CAP 0 x 0 INT
FLA 2 x 0 CFC
AVA 1 x 0 SAN
CEA 3 x 1 COR
JUV 0 x 0 GOI
SAO 2 x 2 FLU
BOT 0 x 1 CAM
ACG 0 x 1 FOR
AME 0 x 3 BRA
PAL 1 x 0 CUI


18ª RODADA
CEA 1 x 0 AVA
BRA 2 x 1 FOR
GOI 2 x 3 FLU
CAP 4 x 1 ACG
FLA 4 x 0 JUV
INT 3 x 3 SAO
COR 3 x 1 CFC
SAN 2 x 0 BOT
CUI 1 x 1 CAM
AME 0 x 1 PAL


19ª RODADA
SAO 3 x 3 GOI
BOT 2 x 0 CAP
AVA 1 x 2 FLA
FLU 2 x 1 BRA
PAL 2 x 1 INT
JUV 1 x 0 CEA
CAM 1 x 2 COR
ACG 0 x 1 AME
FOR 0 x 0 SAN
CFC 1 x 0 CUI


20ª RODADA
CEA 1 x 2 PAL
GOI 1 x 0 CFC
COR 1 x 0 BOT
FLA 4 x 1 ACG
INT 3 x 0 CAM
CAP 1 x 0 SAO
AME 3 x 1 AVA
CUI 0 x 1 FOR
BRA 1 x 0 JUV
SAN 2 x 2 FLU

In [7]:
dataFortheDataFrame = []
for i in teams:
    dataFortheDataFrame.append(teams[i])

df = pd.DataFrame(dataFortheDataFrame)
df = df.sort_values(['pontuacao', 'saldoDeGols', 'id'], ascending=[False, False, True]).style.hide_index()
df